#!/bin/sh

# parse the URL
parse_url() {
  #[scheme://][user[:password]@]host[:port][/path][?params]
  echo "$1" | sed -e "s+^\(\([^:]*\)://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/?]*\)\(:\([^/?]*\)\)\?.*$+ local scheme='\2' username='\4' password='\6' hostname='\7' port='\9'+"
}

java_proxy_options() {
  local url="$1"
  local transport="$2"

  if [ -n "$url" ] ; then
    eval $(parse_url "$url")
    if [ -n "$hostname" ] ; then
      echo "-D${transport}.proxyHost=${hostname}"
    fi
    if [ -n "$port" ] ; then
      echo "-D${transport}.proxyPort=${port}"
    fi
    if [ -n "$username" -o -n "$password" ] ; then
      echo "WARNING: Proxy URL for ${transport} contains authentication credentials, these are not supported by java" >&2
    fi
  fi
}

# Check for proxy options and echo if enabled.
proxy_options() {
  java_proxy_options "${https_proxy:-${HTTPS_PROXY}}" https
  java_proxy_options "${http_proxy:-${HTTP_PROXY}}" http

  local noProxy="${no_proxy:-${NO_PROXY}}"
  if [ -n "$noProxy" ] ; then
    echo "-Dhttp.nonProxyHosts=$(echo $noProxy | sed -e 's+,+|+g')"
  fi
}

proxy_options
